# Basic Information 
title: Lei Chen
position: Postdoctoral Fellow
department: Zhejiang University-University of Edinburgh Institute
affiliation: Zhejiang University
affiliation_link: https://www.zju.edu.cn/
affiliation_logo: ./assets/img/ZJU.png
location: Hangzhou, China
email: leic@intl.zju.edu.cn

# Search Engine Optimization (SEO)
keywords: lei chen, chen lei, leichen, chenlei, alexchancl, nanocellulose, biomaterials, hemostasis
canonical: https://alexchancl.github.io/
description: Lei Chen is a Postdoctoral Fellowat Zhejiang University. His research focuses on bio-based materials, nanocellulose, hemostasis and wound healing, and material recycling.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true


# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=VTr6EA4AAAAJ&hl=en
orcid: https://orcid.org/0000-0003-2732-223X
researchgate: https://www.researchgate.net/profile/Lei-Chen-376
linkedin: https://www.linkedin.com/in/alexchancl
clarivate: https://www.webofscience.com/wos/author/rid/AGD-1835-2022
scopus: https://www.scopus.com/authid/detail.uri?authorId=57770630500
cv_link: ./assets/files/Lei_Chen_CV.pdf
github_link: https://github.com/alexchancl
#twitter: https://twitter.com/

# Images 
avatar: ./assets/img/lei.png
favicon: ./assets/img/favicon.ico
favicon_dark: ./assets/img/favicon.ico

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# The option is used to show the last update time.
enable_last_update: true

# Footnotes
footnote: Lei Chen © 2025 - 2026
# footnote_link: https://quinyim.github.io/

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
#clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME